version: 2

build:
  os: ubuntu-latest
  tools:
    python: "3.13"
  jobs:
    post_install:
      - pip install uv
      - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUAL_ENV_PATH uv sync --all-extras --group docs --link-mode=copy

sphinx:
  configuration: docs/conf.py
  fail_on_warning: true

formats:
  - html