[tox]
envlist =
    check
    py311,
    coverage
    docs

[testenv]
usedevelop = True
extras = test
setenv =
    PYTHONPATH = {toxinidir}
    COVERAGE_FILE=.coverage.{envname}
commands =
    py.test --cov=pystructtype --verbose --tb=long --durations=5 {posargs}

[testenv:coverage]
basepython = python3
deps = coverage[toml]
skip_install = True
skipsdist = True
allowlist_externals = /usr/bin/env
commands =
    /usr/bin/env bash -c "{envpython} -m coverage combine .coverage.*"
    coverage report

[testenv:check]
basepython = python3
extras = check
commands =
    isort pystructtypes tests setup.py --check-only --diff
    black pystructtypes tests setup.py --quiet --check --diff
    flake8 pystructtypes tests setup.py
    mypy pystructtypes setup.py
